hours = input('How many hours do you work? ')
print(hours)
type(hours)
rate = input('How much do you get paid hourly? ')
print(rate)
type(rate)
pay = int(hours) * int(rate)
print('Your pay is', pay)
quit()
